name: fueldey
description: "An app to help users find the nearest fuel stations."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # firebase dependencies
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1

  # state management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  # location and mapping
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  flutter_polyline_points: ^2.1.0

  # time and date
  intl: ^0.20.1
  go_router: ^14.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
